import { Router } from "express";

/* ============================================================
   GROCERY ROUTER (In-Memory Data Store)

   This router manages the Grocery List feature of the app.
   IMPORTANT:
   - This data is stored IN MEMORY, not MongoDB.
   - When the server restarts, the list resets.
   - Angular calls these endpoints through GroceryListService.

   The router is created using a factory function so we can
   inject the shared grocery array and the newId() helper
   from index.js.
============================================================ */

export default function createGroceryRouter({ grocery, newId }) {
  const router = Router();

  /* ------------------------------------------------------------
     GET /api/grocery
     Returns the current grocery list.

     Used by:
     - The grocery list view when loading existing items
  ------------------------------------------------------------ */
  router.get("/", (_req, res) => {
    res.json(grocery);
  });

  /* ------------------------------------------------------------
     POST /api/grocery
     Adds a new grocery item to the in-memory array.

     The item structure:
       {
         id: generated by newId(),
         name: string,
         qty: string or number
       }

     Used by:
     - The "Add Item" form in Angular
  ------------------------------------------------------------ */
  router.post("/", (req, res) => {
    const body = req.body ?? {};

    const item = {
      id: newId(),           // generate unique ID
      name: body.name ?? "", // default empty name
      qty: body.qty ?? "",   // default empty qty
    };

    grocery.push(item);
    res.status(201).json(item);
  });

  /* ------------------------------------------------------------
     DELETE /api/grocery/:id
     Removes a single grocery item by its ID.

     Steps:
       1. Look up the item by ID
       2. Remove it if found
       3. Return 204 No Content on success

     Used by:
     - Delete button on each grocery item
  ------------------------------------------------------------ */
  router.delete("/:id", (req, res) => {
    const idx = grocery.findIndex((g) => g.id === req.params.id);

    if (idx === -1) return res.status(404).json({ message: "Not found" });

    grocery.splice(idx, 1);
    res.status(204).end();
  });

  /* ------------------------------------------------------------
     DELETE /api/grocery
     Clears the ENTIRE grocery list.

     Important detail:
       - We do not reassign the array.
       - Instead, we mutate it in-place (`length = 0`).
       - This keeps references stable for any other modules.

     Used by:
     - "Clear All" button in the UI
  ------------------------------------------------------------ */
  router.delete("/", (_req, res) => {
    grocery.length = 0; // in-place clear so references remain valid
    res.status(204).end();
  });

  return router;
}
